name: Run PR checks
on:
  push:
  workflow_dispatch:

env:
  VITE_PORT: 3000
  API_PORT: 3001
  VITE_API_URL: 'http://localhost:3001'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: npm ci
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key:
            ${{ runner.os }}-node_modules-${{
            hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-node_modules

  jest:
    name: Unit-jest
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v5
      - name: Restore Node Modules Cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key:
            ${{ runner.os }}-node_modules-${{
            hashFiles('**/package-lock.json')}}
      - name: Run Jest
        run: npm run jest

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v5
      - name: Restore Node Modules Cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key:
            ${{ runner.os }}-node_modules-${{
            hashFiles('**/package-lock.json')}}
      - name: Run Lint
        run: npm run lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v5
      - name: Restore Node Modules Cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key:
            ${{ runner.os }}-node_modules-${{
            hashFiles('**/package-lock.json')}}
      - name: Run Typecheck
        run: npm run typecheck
