name: Run ct with cy
on:
  push:
  workflow_dispatch:

env:
  VITE_PORT: 3000
  API_PORT: 3001
  VITE_API_URL: 'http://localhost:3001'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # if you want to enable parallelization
  # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  cy-ct:
    # if you want to enable parallelization
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     machines: [1, 2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cypress component tests
        uses: cypress-io/github-action@v6.7.9
        with:
          component: true
          browser: chrome
          config-file: cypress/config/local.config.ts
          # if you want to enable parallelization
          # record: true
          # parallel: true
          # group: ct-tests
          # tag: ct-tests
